language: node_js
node_js:
  - "10.16.0"
  - "12.5.0"
deploy:
  provider: script
  script: npm run deploy-docs
  skip_cleanup: true
  on:
    branch: develop
    node: "12.5.0"
cache: yarn
notifications:
  slack: augora:NbzHhCF6cj1DOJhe8lGOg5ih
